### ISSUE TITLE
Hexo在安卓手机上使用hexo-all-minifier插件时报错解决方案

### ISSUE THREAD

**Issue by Moriefy** [Moriefy/talks#10]
**报错内容如下**
```
Error: Command failed with ENOENT: /storage/emulated/0/Blog/node_modules/mozjpeg/vendor/cjpeg -baseline
spawn /storage/emulated/0/Blog/node_modules/mozjpeg/vendor/cjpeg ENOENT
```
**解决方案**
1.`mkdir -p /data/data/com.pangbai.weblog/files/usr/tmp`
2.`chmod -R 755 /data/data/com.pangbai.weblog/files/usr/tmp`
3.在_config.yml中添加如下内容
```
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false
```
