### ISSUE TITLE
Hexo-Stellar主题插入支持放大的图片

### ISSUE THREAD

**Issue by Moriefy** [Moriefy/talks#11]
**单张图片支持放大**
- 插入图片(不要用md默认语法）

`{% image src [description] [download:bool/string] [width:px] [padding:px] [bg:hex] [fancybox:bool/string] %}`

> src: 图片地址
description: 图片描述
download: href # 下载地址，设置此值后鼠标放在图片上会显示下载地址，如果下载地址为图片地址，可以设置为 true
width: 200px # 图片宽度
padding: 16px # 图片四周填充宽度
bg: '#ffffff' # 图片区域背景颜色，16进制
fancybox: href # fancybox 放大地址，设置此值后会调用该链接放大，如果放大地址为图片地址，可以设置为 true

- 示例:
`{% image /images/avatar.jpg description download:true fancybox:true %}`

**全局支持图片放大**
- 在_config.stellar.yml中加入如下内容
```
######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true
```

- 示例:`{% image /images/avatar.jpg description download:true %}`

全局的方法可以不用`fancybox:true`这一参数
